import js from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginVue from "eslint-plugin-vue";
import prettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/recommended"],
  prettier,
  {
    files: ["src/**/*.{ts,vue}"],
    languageOptions: {
      globals: {
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        fetch: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        Image: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Text: "readonly",
        ImageData: "readonly",
        CanvasRenderingContext2D: "readonly",
        WebAssembly: "readonly",
        XMLHttpRequest: "readonly",
        WebSocket: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        EventTarget: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        ReadableStream: "readonly",
        WritableStream: "readonly",
        TransformStream: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        crypto: "readonly",
        matchMedia: "readonly",
        history: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        getComputedStyle: "readonly",
        requestIdleCallback: "readonly",
        cancelIdleCallback: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        atob: "readonly",
        btoa: "readonly",
        createImageBitmap: "readonly",
        ImageBitmap: "readonly",
        OffscreenCanvas: "readonly",
        MessageChannel: "readonly",
        MessagePort: "readonly",
        Worker: "readonly",
        SharedWorker: "readonly",
        ServiceWorker: "readonly",
        CacheStorage: "readonly",
        Cache: "readonly",
        IndexedDB: "readonly",
        IDBFactory: "readonly",
        IDBDatabase: "readonly",
        IDBObjectStore: "readonly",
        IDBIndex: "readonly",
        IDBTransaction: "readonly",
        IDBRequest: "readonly",
        IDBCursor: "readonly",
        Notification: "readonly",
        Permission: "readonly",
        Permissions: "readonly",
        Geolocation: "readonly",
        PositionError: "readonly",
        PositionCoordinates: "readonly",
        MediaQueryList: "readonly",
        MediaQueryListEvent: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        PerformanceObserver: "readonly",
        ResizeObserverEntry: "readonly",
        IntersectionObserverEntry: "readonly",
        MutationRecord: "readonly",
        PerformanceEntry: "readonly",
        PerformanceMeasure: "readonly",
        PerformanceMark: "readonly",
        PerformanceResourceTiming: "readonly",
        PerformanceNavigationTiming: "readonly",
        PerformanceLongTaskTiming: "readonly",
        TaskAttributionTiming: "readonly",
        PerformanceServerTiming: "readonly",
        PerformancePaintTiming: "readonly",
        PerformanceTimeline: "readonly",
        PerformanceObserverEntryList: "readonly",
        BigInt64Array: "readonly",
        BigUint64Array: "readonly",
        Float32Array: "readonly",
        Float64Array: "readonly",
        Int8Array: "readonly",
        Int16Array: "readonly",
        Int32Array: "readonly",
        Uint8Array: "readonly",
        Uint8ClampedArray: "readonly",
        Uint16Array: "readonly",
        Uint32Array: "readonly",
        ArrayBuffer: "readonly",
        SharedArrayBuffer: "readonly",
        Atomics: "readonly",
        DataView: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        EvalError: "readonly",
        RangeError: "readonly",
        ReferenceError: "readonly",
        SyntaxError: "readonly",
        TypeError: "readonly",
        URIError: "readonly",
        AggregateError: "readonly",
        Symbol: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Promise: "readonly",
        Generator: "readonly",
        GeneratorFunction: "readonly",
        AsyncFunction: "readonly",
        AsyncGenerator: "readonly",
        AsyncGeneratorFunction: "readonly",
        FinalizationRegistry: "readonly",
        WeakRef: "readonly",
        BigInt: "readonly",
      },
      parserOptions: {
        parser: tseslint.parser,
      },
    },
    rules: {
      "vue/multi-word-component-names": "off",
    },
  },
  {
    ignores: ["dist/", "node_modules/", "src-tauri/target/", "**/*.d.ts"],
  },
];
